package com.example.kotlinnews.model


import android.annotation.SuppressLint
import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import kotlinx.android.parcel.Parcelize
import android.os.Parcelable
import kotlinx.android.parcel.RawValue

@SuppressLint("ParcelCreator")
@Parcelize
@JsonClass(generateAdapter = true)
data class DataX(
    @Json(name = "all_awardings")
    val allAwardings: List<@RawValue Any>? = null,
    @Json(name = "allow_live_comments")
    val allowLiveComments: Boolean? = null,
    @Json(name = "approved_at_utc")
    val approvedAtUtc: @RawValue Any? = null,
    @Json(name = "approved_by")
    val approvedBy:@RawValue Any? = null,
    @Json(name = "archived")
    val archived: Boolean? = null,
    @Json(name = "author")
    val author: String? = null,
    @Json(name = "author_flair_background_color")
    val authorFlairBackgroundColor:@RawValue Any? = null,
    @Json(name = "author_flair_css_class")
    val authorFlairCssClass:@RawValue Any? = null,
    @Json(name = "author_flair_richtext")
    val authorFlairRichtext:@RawValue List<Any>? = null,
    @Json(name = "author_flair_template_id")
    val authorFlairTemplateId:@RawValue Any? = null,
    @Json(name = "author_flair_text")
    val authorFlairText:@RawValue Any? = null,
    @Json(name = "author_flair_text_color")
    val authorFlairTextColor:@RawValue Any? = null,
    @Json(name = "author_flair_type")
    val authorFlairType: String? = null,
    @Json(name = "author_fullname")
    val authorFullname: String? = null,
    @Json(name = "author_patreon_flair")
    val authorPatreonFlair: Boolean? = null,
    @Json(name = "author_premium")
    val authorPremium: Boolean? = null,
    @Json(name = "awarders")
    val awarders: List<@RawValue Any>? = null,
    @Json(name = "banned_at_utc")
    val bannedAtUtc:@RawValue Any? = null,
    @Json(name = "banned_by")
    val bannedBy: @RawValue Any? = null,
    @Json(name = "can_gild")
    val canGild: Boolean? = null,
    @Json(name = "can_mod_post")
    val canModPost: Boolean? = null,
    @Json(name = "category")
    val category: @RawValue Any? = null,
    @Json(name = "clicked")
    val clicked: Boolean? = null,
    @Json(name = "content_categories")
    val contentCategories: @RawValue Any? = null,
    @Json(name = "contest_mode")
    val contestMode: Boolean? = null,
    @Json(name = "created")
    val created: Int? = null,
    @Json(name = "created_utc")
    val createdUtc: Int? = null,
    @Json(name = "discussion_type")
    val discussionType: @RawValue Any? = null,
    @Json(name = "distinguished")
    val distinguished: @RawValue Any? = null,
    @Json(name = "domain")
    val domain: String? = null,
    @Json(name = "downs")
    val downs: Int? = null,
    @Json(name = "edited")
    val edited: @RawValue Any? = null,
    @Json(name = "gilded")
    val gilded: Int? = null,
    @Json(name = "gildings")
    val gildings: Gildings? = null,
    @Json(name = "hidden")
    val hidden: Boolean? = null,
    @Json(name = "hide_score")
    val hideScore: Boolean? = null,
    @Json(name = "id")
    val id: String? = null,
    @Json(name = "is_crosspostable")
    val isCrosspostable: Boolean? = null,
    @Json(name = "is_meta")
    val isMeta: Boolean? = null,
    @Json(name = "is_original_content")
    val isOriginalContent: Boolean? = null,
    @Json(name = "is_reddit_media_domain")
    val isRedditMediaDomain: Boolean? = null,
    @Json(name = "is_robot_indexable")
    val isRobotIndexable: Boolean? = null,
    @Json(name = "is_self")
    val isSelf: Boolean? = null,
    @Json(name = "is_video")
    val isVideo: Boolean? = null,
    @Json(name = "likes")
    val likes: @RawValue Any? = null,
    @Json(name = "link_flair_background_color")
    val linkFlairBackgroundColor: String? = null,
    @Json(name = "link_flair_css_class")
    val linkFlairCssClass: @RawValue Any? = null,
    @Json(name = "link_flair_richtext")
    val linkFlairRichtext: List<@RawValue Any>? = null,
    @Json(name = "link_flair_text")
    val linkFlairText: @RawValue Any? = null,
    @Json(name = "link_flair_text_color")
    val linkFlairTextColor: String? = null,
    @Json(name = "link_flair_type")
    val linkFlairType: String? = null,
    @Json(name = "locked")
    val locked: Boolean? = null,
    @Json(name = "media")
    val media: Media? = null,
    @Json(name = "media_embed")
    val mediaEmbed: MediaEmbed? = null,
    @Json(name = "media_metadata")
    val mediaMetadata: MediaMetadata? = null,
    @Json(name = "media_only")
    val mediaOnly: Boolean? = null,
    @Json(name = "mod_note")
    val modNote: @RawValue Any? = null,
    @Json(name = "mod_reason_by")
    val modReasonBy: @RawValue Any? = null,
    @Json(name = "mod_reason_title")
    val modReasonTitle: @RawValue Any? = null,
    @Json(name = "mod_reports")
    val modReports: @RawValue List<Any>? = null,
    @Json(name = "name")
    val name: String? = null,
    @Json(name = "no_follow")
    val noFollow: Boolean? = null,
    @Json(name = "num_comments")
    val numComments: Int? = null,
    @Json(name = "num_crossposts")
    val numCrossposts: Int? = null,
    @Json(name = "num_reports")
    val numReports: @RawValue Any? = null,
    @Json(name = "over_18")
    val over18: Boolean? = null,
    @Json(name = "parent_whitelist_status")
    val parentWhitelistStatus: String? = null,
    @Json(name = "permalink")
    val permalink: String? = null,
    @Json(name = "pinned")
    val pinned: Boolean? = null,
    @Json(name = "pwls")
    val pwls: Int? = null,
    @Json(name = "quarantine")
    val quarantine: Boolean? = null,
    @Json(name = "removal_reason")
    val removalReason: @RawValue Any? = null,
    @Json(name = "removed_by")
    val removedBy: @RawValue Any? = null,
    @Json(name = "removed_by_category")
    val removedByCategory: @RawValue Any? = null,
    @Json(name = "report_reasons")
    val reportReasons: @RawValue Any? = null,
    @Json(name = "saved")
    val saved: Boolean? = null,
    @Json(name = "score")
    val score: Int? = null,
    @Json(name = "secure_media")
    val secureMedia: @RawValue Any? = null,
    @Json(name = "secure_media_embed")
    val secureMediaEmbed: SecureMediaEmbed? = null,
    @Json(name = "selftext")
    val selftext: String? = null,
    @Json(name = "selftext_html")
    val selftextHtml: String? = null,
    @Json(name = "send_replies")
    val sendReplies: Boolean? = null,
    @Json(name = "spoiler")
    val spoiler: Boolean? = null,
    @Json(name = "stickied")
    val stickied: Boolean? = null,
    @Json(name = "subreddit")
    val subreddit: String? = null,
    @Json(name = "subreddit_id")
    val subredditId: String? = null,
    @Json(name = "subreddit_name_prefixed")
    val subredditNamePrefixed: String? = null,
    @Json(name = "subreddit_subscribers")
    val subredditSubscribers: Int? = null,
    @Json(name = "subreddit_type")
    val subredditType: String? = null,
    @Json(name = "suggested_sort")
    val suggestedSort: @RawValue Any? = null,
    @Json(name = "thumbnail")
    val thumbnail: String? = null,
    @Json(name = "title")
    val title: String? = null,
    @Json(name = "top_awarded_type")
    val topAwardedType: @RawValue Any? = null,
    @Json(name = "total_awards_received")
    val totalAwardsReceived: Int? = null,
    @Json(name = "treatment_tags")
    val treatmentTags: List<@RawValue Any>? = null,
    @Json(name = "ups")
    val ups: Int? = null,
    @Json(name = "upvote_ratio")
    val upvoteRatio: Double? = null,
    @Json(name = "url")
    val url: String? = null,
    @Json(name = "user_reports")
    val userReports: List<@RawValue Any>? = null,
    @Json(name = "view_count")
    val viewCount: @RawValue Any? = null,
    @Json(name = "visited")
    val visited: Boolean? = null,
    @Json(name = "whitelist_status")
    val whitelistStatus: String? = null,
    @Json(name = "wls")
    val wls: Int? = null
) : Parcelable